name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: zulu
          cache: gradle

      - name: Build mod
        run: |
          chmod +x ./gradlew && ./gradlew build --no-daemon

      - name: Upload mod as artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
